from datetime import datetime
from typing import Optional, List
from enum import Enum
from sqlalchemy import Column, String, Integer, DateTime, Text, Boolean, ForeignKey, Float, Index, JSON
from sqlalchemy.orm import declarative_base, relationship
from sqlalchemy.sql import func

Base = declarative_base()

class PipelineStatus(str, Enum):
    """
    The distinct states a domain can be in.
    This drives the Dashboard Visualization and Bottleneck Detection.
    """
    DISCOVERED = "DISCOVERED"       # Found in a feed/uploaded, waiting for action
    BLOCKED = "BLOCKED"             # Stopped by Whitelist/Blacklist
    QUEUED = "QUEUED"               # Scheduled for processing
    CRAWLING = "CRAWLING"           # Browser/Request is active
    CRAWLED_SUCCESS = "CRAWLED_SUCCESS"
    CRAWLED_FAIL = "CRAWLED_FAIL"
    PROCESSING = "PROCESSING"       # Parsing HTML, determining relevance
    ANALYZING = "ANALYZING"         # Sent to LLM
    ANALYSIS_SUCCESS = "ANALYSIS_SUCCESS"
    ANALYSIS_FAIL = "ANALYSIS_FAIL"
    INDEXING = "INDEXING"           # Adding to Vector DB
    COMPLETED = "COMPLETED"         # Successfully in KB
    ARCHIVED = "ARCHIVED"           # Old data, kept for record

class PriorityLevel(int, Enum):
    CRITICAL = 1  # User manual request
    HIGH = 2      # Hot feed (e.g., PhishStats last 1h)
    MEDIUM = 3    # Standard feed
    LOW = 4       # Bulk import history

class PipelineItem(Base):
    """
    The Master Table.
    Every row is one FQDN.
    """
    __tablename__ = "pipeline_items"

    id = Column(Integer, primary_key=True, index=True)
    fqdn = Column(String, unique=True, index=True, nullable=False)
    
    # Tracking
    status = Column(String, default=PipelineStatus.DISCOVERED, index=True) # PipelineStatus Enum
    source = Column(String, default="manual") # e.g., 'urlhaus', 'csv_import'
    batch_id = Column(String, nullable=True) # To group items added together
    
    # Scheduling & Resilience
    priority = Column(Integer, default=PriorityLevel.MEDIUM)
    retry_count = Column(Integer, default=0)
    max_retries = Column(Integer, default=3)
    next_retry_at = Column(DateTime, nullable=True) # For exponential backoff
    
    # Timestamps for "Bottleneck Detection"
    # If (now - updated_at) > Threshold AND status in [CRAWLING, ANALYZING], it's STUCK.
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now(), index=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    crawl_result = relationship("CrawlResult", uselist=False, back_populates="item")
    analysis_result = relationship("AnalysisResult", uselist=False, back_populates="item")
    logs = relationship("PipelineLog", back_populates="item")

class CrawlResult(Base):
    """
    Stores the raw evidence from the crawler.
    Separated from Item to keep the main table light.
    """
    __tablename__ = "crawl_results"

    id = Column(Integer, primary_key=True, index=True)
    item_id = Column(Integer, ForeignKey("pipeline_items.id"), unique=True)
    
    url = Column(String) # The final URL (after redirects)
    http_status = Column(Integer)
    title = Column(String, nullable=True)
    
    # Content
    html_content_path = Column(String, nullable=True) # Store file path, not huge blob in DB
    screenshot_path = Column(String, nullable=True)
    content_hash = Column(String, index=True) # To detect duplicates
    
    crawled_at = Column(DateTime(timezone=True), server_default=func.now())
    
    item = relationship("PipelineItem", back_populates="crawl_result")

class AnalysisResult(Base):
    """
    The Intelligence generated by the system (LLM).
    """
    __tablename__ = "analysis_results"

    id = Column(Integer, primary_key=True, index=True)
    item_id = Column(Integer, ForeignKey("pipeline_items.id"), unique=True)
    
    # Classification
    is_malicious = Column(Boolean, default=False)
    confidence_score = Column(Float, default=0.0)
    
    category_main = Column(String, index=True) # e.g., "Phishing"
    category_detailed = Column(String) # e.g., "Bank Credential Theft"
    
    # LLM Details (for cost/performance tracking)
    llm_model_used = Column(String) # e.g., "ollama/llama3"
    processing_time_ms = Column(Integer)
    
    # RAG/KB Info
    vector_id = Column(String, nullable=True) # ID in ChromaDB/Qdrant
    
    summary = Column(Text, nullable=True)
    
    analyzed_at = Column(DateTime(timezone=True), server_default=func.now())
    
    item = relationship("PipelineItem", back_populates="analysis_result")

class PipelineLog(Base):
    """
    A granular history of what happened to this item.
    Crucial for "Why did this fail?" debugging in GUI.
    """
    __tablename__ = "pipeline_logs"

    id = Column(Integer, primary_key=True, index=True)
    item_id = Column(Integer, ForeignKey("pipeline_items.id"))
    
    stage = Column(String) # e.g., "CRAWLER", "LLM"
    level = Column(String) # INFO, ERROR, WARNING
    message = Column(Text)
    
    timestamp = Column(DateTime(timezone=True), server_default=func.now())
    
    item = relationship("PipelineItem", back_populates="logs")

class SystemMetric(Base):
    """
    For the "Health" Dashboard.
    Records system state every N minutes.
    """
    __tablename__ = "system_metrics"
    
    id = Column(Integer, primary_key=True)
    timestamp = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    
    cpu_usage_percent = Column(Float)
    memory_usage_percent = Column(Float)
    gpu_usage_percent = Column(Float, nullable=True)
    
    # Pipeline Health
    pending_queue_size = Column(Integer)
    active_crawlers = Column(Integer)
    failed_last_hour = Column(Integer)
    
class DomainFilter(Base):
    """
    Whitelist / Blacklist management.
    """
    __tablename__ = "domain_filters"
    
    id = Column(Integer, primary_key=True)
    pattern = Column(String, unique=True) # e.g., "*.google.com" or "example.com"
    type = Column(String) # WHITELIST, BLACKLIST
    description = Column(String)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, server_default=func.now())
